
services:
  reader-springboot:
    container_name: reader-springboot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8081:8081"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    volumes:
      - ./docker-volume/logs:/app/logs
    restart: unless-stopped
    networks:
      - bankingnet
      
networks:
  bankingnet:
    external: true
